# Generated by Django 4.2.1 on 2023-05-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issue_tracking_system", "0002_delete_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=255)),
                ("priority", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Issues",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Projects",
            },
        ),
    ]
