# Generated by Django 4.2.1 on 2023-05-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracking_system", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issue",
        ),
    ]
