# Generated by Django 4.2.1 on 2023-05-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracking_system", "0005_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Comments",
            },
        ),
    ]
