# Generated by Django 4.2.1 on 2023-05-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracking_system", "0006_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Contributors",
            },
        ),
    ]
