# Generated by Django 4.2.1 on 2023-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracking_system", "0023_alter_comment_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("backend", "Back-end"),
                    ("frontend", "Front-end"),
                    ("ios", "IOS"),
                    ("Android", "Android"),
                ],
                max_length=255,
            ),
        ),
    ]
