# Generated by Django 4.2.1 on 2023-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracking_system", "0025_alter_issue_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("BUG", "Bug"),
                    ("IMPROUVMENT", "Improuvment"),
                    ("TASK", "Task"),
                ],
                max_length=255,
            ),
        ),
    ]
