# Generated by Django 4.2.1 on 2023-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracking_system", "0026_alter_issue_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("TODO", "Todo"), ("CURRENT", "Current"), ("END", "End")],
                max_length=255,
            ),
        ),
    ]
